project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "POLS0113: Judicial Politics"
  page-navigation: true
  page-footer: 
    border: true
    right: "Website by Michal Ovádek, built with Quarto"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Overview"
        href: index.qmd
      - "assessment.qmd"
      - "seminars.qmd"
      - text: "FAQ"
        href: faq.qmd
      - text: "Data resources"
        href: data-res.qmd  
      - section: Weeks
        contents: 
          auto: "week*.qmd"

execute:
  echo: false

format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: source
