---
title: "Assessment"
---

The module is assessed by one compulsory **research paper of 3000 words** worth 100% of the final mark. The deadline and submission instructions for the assessment can be found on the module's Moodle page.

The research paper must be **empirical** in nature. This means the research has to rely on observable evidence to answer a question about an aspect of judicial politics. The research design devised to answer the research question can be quantitative, qualitative or mixed.

The best research questions will follow from and attempt to contribute to scholarly literature on a phenomenon of broader theoretical interest. Even when the paper's empirical part focuses on just a single case study, it should be made clear what broader phenomenon the case is meant to be an instance of. The research question should result from the identification of a research gap in the literature. The answer to the research question should not be obvious or found in existing academic work.

The introduction to the paper should explicitly motivate why the phenomenon of interest is important (socially, politically, economically, normatively) to study. The introduction should also explain what the key issue or puzzle which need investigating is.

Each research paper must include one section discussing **theory** and one section discussing **research design**. The theory section sets out the researcher's expectations about the studied phenomenon on the basis of existing academic literature and typically ends with a testable hypothesis. The research design section describes how the research question will be answered and must include a discussion of the information (data) and the method (e.g. process tracing or regression analysis) used to produce evidence in support of (or against) a hypothesis. The theory and research design need to be selected so as to be appropriate to the research question.

The findings produced by the empirical analysis should be presented in a separate section for clarity. Thereafter they should be discussed in terms of the hypothesis, the research question and finally related back to the scholarly literature to which the paper is contributing.

Papers are expected to use an author-year (in-text) citation system. Citation and reference formatting should follow the [Chicago style](https://www.chicagomanualofstyle.org/home.html). The list of references at the end of the document are not counted towards the word limit (but the in-text citations are). Any footnotes or endnotes count towards the word limit. Compliance with university plagiarism policies is a must.

The module's schedule requires continuous work on the assessment from week 1 until submission date. The following table outlines a possible workflow for writing a good final paper:

| Weeks | Objective | Tasks |
|----------|--------------------------|------------------------------------|
| 1 – 2 | Find a research topic | Skim the module's contents, including suggested readings in areas of interest; make notes on findings and questions encountered |
| 3 – 4 | Review literature | Summarize at least 15 relevant academic publications; identify gaps in the literature; formulate a specific research question answerable with data; build on existing theories to propose a testable hypothesis |
| 5 – 6 | Propose a research design | Choose an empirical strategy to answer your research question; find suitable data to test your hypothesis; choose a specific methodology for data analysis; create a work-in-progress paper with at least headings |
| 7 – 8 | Solicit feedback | Obtain feedback on your research question, hypothesis and proposed research design; update the work-in-progress paper in light of suggestions and new information |
| 7 – 8 | Collect data | Create a repository with all the data needed to execute your research design; check the completeness and accuracy of the data; clean the data in preparation for analysis; take notes on data provenance, quality and limitations |
| 9 – 10 | Analyse data | Apply the chosen analytical method to the data; report the results; interpret the findings in light of the hypothesis and broader theory; check how robust the results are to alternative methodological specifications; create an appendix with supporting information on the analytical process |
| 10 – submission | Draft and edit final paper | Expand your notes into a full paper; add previously missed literature; make adjustments in light of new information; carefully review and revise the full paper; polish language and formatting; submit on time |

### General assessment criteria

In addition to the above requirements, the markers will consider the following criteria when assessing the paper:

-   Structure and organisation

-   Extent of research work completed

-   Use of evidence

-   Development and consistency of arguments

-   Evidence of critical analysis

-   Overall insight and originality

-   Adequacy and presentation of bibliographic information

-   Accuracy and appropriateness of referencing

-   Overall presentation

An excellent essay will be strong on each criterion.

### Use of artificial intelligence tools

The work submitted for assessment is not allowed to have been generated by artificial intelligence tools. Failure to abide by this requirement will be treated as academic misconduct and trigger the relevant procedures and penalties. Standard academic misconduct regulations apply at all times.

The use of artificial intelligence and machine learning tools is allowed insofar as it forms part of the methodological approach, such as using GPT models for text classification to measure a concept of interest.

### Assessment tips {#assessment-tips}

Below is a non-exhaustive list of tips to help you write a better paper:

-   [ ] Imagine you are a researcher writing a short empirical paper for an academic journal in political science

-   [ ] Original (your own) empirical work must be the centrepiece of the paper -- this means demonstrating deep engagement with primary sources such as court decisions, government documents, parliamentary speeches, media coverage, etc

-   [ ] What about judicial politics do we not know or understand yet and how does your paper help address the gap? Be concrete about your contribution

-   [ ] Be clear about what is new in your paper -- is it the data? Is it the theory? Is it the analytical method?

-   [ ] Write in an academic style with a [focus on clarity above all else](https://catherineeunicedevries.substack.com/p/the-hidden-gift-of-fewer-words)

-   [ ] Don't submit your paper until you have carefully [revised and edited it](https://catherineeunicedevries.substack.com/p/editing-the-work-beneath-the-words)

-   [ ] When reviewing academic literature, take into account the reputation (importance and trustworthiness) of the source you are relying on. Avoid using articles from predatory and low-reputation [journals](https://www.scimagojr.com/journalrank.php?category=3320)

-   [ ] Make sure your literature review covers all relevant academic scholarship on your subject, including the most recently published articles

-   [ ] The lecture slides are just an entry point to the field -- your research and paper need to go deeper

-   [ ] Key concepts in your theory need to be clearly defined early on

-   [ ] If you are following a qualitative methodology, your paper should come with a [transparency appendix](https://doi.org/10.1017/S1049096513001789) that details how you assessed pieces of evidence and made analytical decisions, as well as a [codebook](https://doi.org/10.1017/S1049096524000714) if you are assigning codes or categories

-   [ ] If you are following a quantitative methodology, you should [publish replication materials](https://doi.org/10.1017/S1049096521001062) (data and programming code) in an online repository and include a link to them in the paper

-   [ ] Whenever you are working with a sample of cases as your empirical material -- which will be almost always -- you need to explain how you made the selection, how it fits with your research design and how it serves your research question

-   [ ] How does your theoretical argument and your empirical observation generalize to other cases? What are the scope conditions of your theory, i.e. where and when does your theory apply?

-   [ ] Specific references (e.g. citations including the page number) are better than general references

-   [ ] Format your paper, including in-text citations and bibliography, correctly and consistently. When in doubt, consult the [Chicago Manual of Style](https://www.chicagomanualofstyle.org/home.html)

-   [ ] Your paper needs to have a title -- a hypothesis is not a title

-   [ ] Don't use bullet points -- write in full sentences and paragraphs instead

-   [ ] An assumption is something taken for granted (e.g. to simplify a problem), while a hypothesis is a proposed explanation meant to be tested

-   [ ] Hypotheses are tested, not "proven" -- your findings can be more or less (in)consistent with a hypothesis

-   [ ] Whether your findings support or contradict a theory is not material to the assessment, as long as you are sincerely trying to answer a relevant and reasoned question rooted in the literature

-   [ ] Use figures and tables to summarize and communicate information where appropriate
