---
title: "Data resources"
---

When doing research on courts and judicial politics, the following (non-exhaustive) list of databases and resources might be useful:

-   [Dataverse of the Journal of Law and Courts](https://dataverse.harvard.edu/dataverse/jlc)
-   [The US Supreme Court Database](http://scdb.wustl.edu/)
-   [The US Supreme Court Justices Database](https://epstein.wustl.edu/justicesdata)
-   [The US Supreme Court Shadow Docket Database](https://www.shadowdocketdata.com/)
-   [CourtListener (US Case Law and Judges Database)](https://www.courtlistener.com/)
-   [The Constitute Project](https://www.constituteproject.org/)
-   [Comparative Constitutions Project](https://comparativeconstitutionsproject.org/)
-   [The German Constitutional Court Database](https://ccdb.eu/)
-   [Varieties of Democracy](https://v-dem.net/data/the-v-dem-dataset/)
-   [IUROPA CJEU Database](https://www.iuropa.pol.gu.se/)
-   [CompLaw: Comparative Study of Judicial Review](https://doi.org/10.7910/DVN/STT55X)
-   [International Court of Justice Corpora](https://onlinelibrary.wiley.com/doi/full/10.1111/jels.12313)
-   [The Czech Constitutional Court Database](https://www.cambridge.org/core/journals/journal-of-law-and-courts/article/czech-constitutional-court-database/E3BA7816D8C221C3A13CF843E2526BA1)
-   [The Hungarian Constitutional Court Database](https://link.springer.com/article/10.1007/s13132-023-01395-6)
-   [Database on the Inter-American Court of Human Rights](https://www.cambridge.org/core/journals/journal-of-law-and-courts/article/law-and-politics-in-the-interamerican-court-of-human-rights/D8626134C5CA187D2C90CF29EF27D752)
-   [Corpus of Bundesfinanzhof Decisions](https://zenodo.org/records/14622341)
-   [Members and Destinations of Spain's Judiciary](https://zenodo.org/records/13987475)
-   [Discretionary Appointments to Spain's Judiciary](https://zenodo.org/records/13991514)
-   [UK Supreme Court Decisions](https://zenodo.org/records/17207970)
-   [Swiss Federal Supreme Court Dataset](https://doi.org/10.5281/zenodo.14867950)
-   [Criminal Cases from Wisconsin Circuit Courts](https://clezdata.github.io/wcld/)

Before spending time on collecting your own data, make sure to check whether an existing database cannot be leveraged for your research question.

More generally, going beyond existing databases when working on the final paper is encouraged but not strictly required. Original data collection can constitute an important contribution, however.

### Data tips

- in general, more granular data is preferred to aggregated data because it enables attending to potentially important details. For example, having data on judicial decisions at the individual case level is more useful than a monthly summary of how many decisions a given court rendered. The latter can be constructed from the former but not vice versa

- when using the texts of judicial opinions (decisions) as data, it is important to keep in mind the limitations of and necessary assumptions for basing inferences on them. The text of a judicial opinion is unlikely to be a sincere representation of the full deliberation and process that led to the decision. In contrast, it is quite likely that the judicial opinion is written as a form of motivated reasoning to justify the court's preferred outcome. The choice of what is (not) included in the final opinion can therefore be highly strategic. It is very likely that the text (including citations) does not contain the full set of considerations which shaped the judicial outcome

- given the limitations of using judicial opinions, empirical research frequently focuses on judicial outcomes. Regardless of the reasoning revealed in the judicial opinion, outcomes of court cases are generally expected to be consequential, at least for the parties to the case and potentially beyond. The most consequential outcomes tend to be *dispositions* that reveal which party won the case, whether someone was found guilty of a crime, the length of a prison sentence, etc. Less obviously, a case outcome may also be the creation or amendment of a legal *rule* 
