---
title: "POLS0113: Judicial Politics"
author: "Dr Michal Ovádek"
date-modified: today
date-format: "D MMMM YYYY"
author-title: "Module Convenor"
published-title: "Last Modified"
---

This is a website for the module `{{< meta title >}}` convened at the [Department of Political Science](https://www.ucl.ac.uk/political-science/), University College London by [{{< meta author >}}](https://michalovadek.github.io/).

```{r global}
# current date
now_date <- Sys.Date()
now_year <- substr(now_date, 1, 4)

# first and last lecture dates
first_lecture <- "29 September"
last_lecture <- "8 December"

# day time
day <- "Monday"
time_1 <- "15:00--16:00"
time_2 <- "16:00--17:00"
time_3 <- "17:00--18:00"

# weeks
weeks <- ifelse(grepl("Sept", first_lecture), "6--10, 12--16", "21--25, 27--31")

# rooms
room_1 <- "UCL ICH, Wolfson Centre, F11"
room_2 <- "UCL ICH, Wellcome Trust Building, Levinsky Room, 30 Guildford St"
```

## Description

This course provides a detailed exploration of judicial politics across a variety of political systems. As predominantly non-majoritarian institutions, both domestic and international courts have become increasingly contested in recent years. We will seek to understand the importance and behaviour of courts from different angles: judiciaries’ place in democratic theory, the design of judicial institutions, and judges’ interactions with other political actors and society more broadly. Among others, we will be delving into why and how politicians balance delegating decision-making to courts with constraining their room for manoeuvre through appointment procedures and threat of override. We will also compare the institutional features of judiciaries across different political contexts, from democracies to autocracies and from presidential to parliamentary systems. The aim is to equip students with a clear understanding of courts as both subjects and objects of their political environment.

|                 |                                 |
|-----------------|---------------------------------|
| Module Name     | Judicial Politics               |
| Module Code     | POLS0113                        |
| Module Convenor | Dr Michal Ovádek                |
| Faculty         | Social and Historical Sciences  |
| Department      | Political Science               |
| Credits         | 15                              |
| Assessment      | 3000-word research paper (100%) |

## Timetable

The first lecture takes place on `r paste(first_lecture, now_year)`. The last lecture is on `r paste(last_lecture, now_year)`. There are no classes during the reading week.

| Weeks | What | When | Where |
|----|----|----|----|
| `r weeks` | Lecture | `r day`, `time_1` | `r room_1` |
| `r weeks` | Seminar 1 | `r day`, `time_2` | `r room_2` |
| `r weeks` | Seminar 2 | `r day`, `time_3` | `r room_2` |

Student support and feedback hours take place after seminar 2 in Room 202, 36 Gordon Square.
