---
title: "Seminars"
---

The seminars consist of two activities. First, students **present** in groups of two a comparison of courts from multiple jurisdictions. Second we **discuss** the week's mandatory readings.

## Presentations

In teaching weeks 2 to 10, student presentations are given on courts in a comparative perspective. These presentations are **formative** (not marked). Nonetheless, they play an important role in the module. They ensure that the class attains an overview of judicial politics across different national and international contexts. They also give the presenting students an opportunity to familiarize themselves with empirical research before the final paper.

Students present in groups of two with each student covering **one specific court** within a specific region (see below). The chosen courts should preferably hold high importance in the judicial system of a country or international organization (e.g. peak courts) and be mutually comparable. The presenting group concludes the presentation with a comparison of the selected courts. The full presentation should take 25 minutes in total.

To enable a structured comparison of courts across different jurisdictions, each student chooses a specific court -- preferably at the same level of hierarchy -- from the week's region on which they collect and present answers to at least the following questions:

-   At which level of hierarchy does the court operate?

-   How many judges work at the court?

-   How are the judges appointed?

-   What are the court's resources? (e.g. its annual budget)

-   Does the court have discretion over which cases it decides? (i.e. docket control)

-   How many cases a year does the court decide on average?

-   Is it possible to appeal the court's decisions?

-   Are judges' votes public?

-   Does the court speak with a single voice or are dissents allowed?

-   How supportive is the public of the court?

In the final part of the presentation, the presenting group should reflect on what we can learn about judicial politics based on the similarities and differences between the courts. For example, the group might want to consider the extent to which different appointment procedures manifest in different ideological compositions of a court (or any other aspect of judicial politics).

Students can indicate their preference for a week via email or in the seminar of week 1 on a first-come-first-serve basis. All remaining students will be randomly assigned to available spots.

::: panel-tabset
### Seminar 1

| Teaching week | Region             | Presenters |
|---------------|--------------------|------------|
| 2             | North America      |    Grace, Paige        |
| 3             | Western Europe     |       Sasha, Victoria K    |
| 4             | Eastern Europe     |     Alexandra I, Louisa       |
| 5             | East Asia          |      Annabel, Theodore      |
| 6             | Southeast Asia     |       Piti, Aadavha     |
| 7             | Sub-Saharan Africa |     Victoria R, Blanche, Elleda    |
| 8             | North Africa       |        Maya, Tess, Jama    |
| 9             | South America      |       Luke, Lila   |
| 10            | International      |      Ambrine, Margot      |

### Seminar 2

| Teaching week | Region             | Presenters |
|---------------|--------------------|------------|
| 2             | North America      |     Sebastian, Charlie       |
| 3             | Western Europe     |      Rebecca, Eli      |
| 4             | Eastern Europe     |    Mathilde, Tamsin        |
| 5             | East Asia          |       Murph, Violet     |
| 6             | Southeast Asia     |     Abigail, Norah     |
| 7             | Sub-Saharan Africa |    Madhav, Lemuel, Emma        |
| 8             | North Africa       |     Mustafa, Will       |
| 9             | South America      |    Carolina, Alexandra R        |
| 10            | International      |      Mary, Yasma      |
:::

Each court can only be covered **once** – there can be no repeat presentations of the same court in the same seminar group. All students should establish contact with their co-presenters as soon as possible.

## Readings

In each teaching week there is an assigned mandatory reading which students are expected to read and be prepared to discuss in class. There is also an additional list of optional readings which represent a good starting point to the literature on the topic of the week, but do not assume they are exhaustive (i.e. there are other papers on the topic). Further readings are featured in lecture slides.

The length of the mandatory reading list is kept modest so that students have more time to dive deeper into specific topics of interest, which is essential for the final paper in particular, as it needs to be grounded in existing academic literature. The theories and methodologies used in the mandatory and optional readings should also be approached as a source of inspiration for the final paper.

For each mandatory reading, each student should be prepared to discuss in the seminar the following questions:

-   what is the main theoretical problem the paper aspires to contribute to?

-   what observed phenomena are the authors trying to explain?

-   what is the theoretical explanation of the observed phenomena the authors advance?

-   to what extent do the empirical results support the theory?

-   in what ways do the findings support or contradict previous studies?
