---
title: "7: Judicial Hierarchy and Organization"
---

Judicial systems typically resemble pyramids: courts at each layer of the hierarchy are subject to oversight by courts in the layer above, except for the courts at the apex of the pyramid. This week we discuss the differences between higher and lower courts and the impact of judicial hierarchy on decision-making.

## Mandatory readings

Carrubba, Clifford J., and Tom S. Clark. "Rule creation in a political hierarchy." *American Political Science Review* 106, no. 3 (2012): 622-643.

## Optional readings

Beim, Deborah. "Learning in the judicial hierarchy." *The Journal of Politics* 79, no. 2 (2017): 591-604.

Zorn, Christopher, and Jennifer Barnes Bowie. "Ideological influences on decision making in the federal judicial hierarchy: An empirical assessment." *The Journal of Politics* 72, no. 4 (2010): 1212-1221.

Scott, Kevin M. "Understanding judicial hierarchy: Reversals and the behavior of intermediate appellate judges." *Law & Society Review* 40, no. 1 (2006): 163-192.

Fjelstul, Joshua C. "How the Chamber System at the CJEU Undermines the Consistency of the Court’s Application of EU Law." *Journal of Law and Courts* 11, no. 1 (2023): 141-162.

Posner, Richard A. "An economic approach to legal procedure and judicial administration." *The Journal of Legal Studies* 2, no. 2 (1973): 399-458.

Lax, Jeffrey R. "Constructing legal rules on appellate courts." *American Political Science Review* 101, no. 3 (2007): 591-604.

Kastellec, Jonathan P. "Racial diversity and judicial influence on appellate courts." *American Journal of Political Science* 57, no. 1 (2013): 167-183.

Masood, Ali S., Benjamin J. Kassow, and Donald R. Songer. "Supreme Court precedent in a judicial hierarchy." *American Politics Research* 45, no. 3 (2017): 403-434.

Songer, Donald R., Jeffrey A. Segal, and Charles M. Cameron. "The hierarchy of justice: Testing a principal-agent model of Supreme Court-circuit court interactions." *American Journal of Political Science* 38, no. 3 (1994): 673-696.

Lax, Jeffrey R. "Political constraints on legal doctrine: How hierarchy shapes the law." *The Journal of Politics* 74, no. 3 (2012): 765-781.

Pavone, Tommaso. "Revisiting judicial empowerment in the European Union: Limits of empowerment, logics of resistance." *Journal of Law and Courts* 6, no. 2 (2018): 303-331.

Goto, Jun. "Career incentives and judicial independence: Evidence from the Indian lower judiciary." *Journal of Development Economics* (2025): 103571.

## Lecture slides

<!-- [Week 7](lectures/07-judicial-hierarchy.html) -->