---
title: "1: Reasons for Courts"
---

What are courts and what is their purpose in society and politics? Mohr defines courts as

> a family of passive governmental institutions one of whose prominent functions is the settlement of disputes, distinguished from other governmental institutions by a commitment to decide impartially, after presentation of proofs and arguments by contending parties, and to be able to justify decisions according to pre-existing rule.[^1]

[^1]: Mohr, Lawrence B. "Organizations, decisions, and courts." *Law & Society Review* 10, no. 4 (1976): 621-642, p. 623.

In this session we reflect on the intended functions of courts in societies, their history, common typologies of courts and why they are relevant for the study of politics.

## Mandatory readings

Waldron, Jeremy. "The rule of law and the role of courts." *Global Constitutionalism* 10, no. 1 (2021): 91-105.

## Optional readings

Epstein, Lee, Olga Shvetsova, and Jack Knight. "The role of constitutional courts in the establishment and maintenance of democratic systems of government." *Law & Society Review* 35, no. 1 (2001): 117-163.

Messick, Richard E. "The Origins and Development of Courts." *Judicature* 85, no. 4
(2002): 175-181.

Carugati, Federica, Gillian K. Hadfield, and Barry R. Weingast. "Building legal order in ancient Athens." *Journal of Legal Analysis* 7, no. 2 (2015): 291-324.

Fleck, Robert K., and F. Andrew Hanssen. "The emergence of democratic constitutions: comparing the modern world to ancient Greece." *Public Choice* (2025): 1-38.

Fleck, Robert K. and Hanssen, F. Andrew. "On the Benefits and Costs of Legal Expertise: Adjudication in Ancient Athens" *Review of Law & Economics* 8, no. 2 (2012): 367-399.

Milgrom, Paul R., Douglass C. North, and Barry R. Weingast. "The role of institutions in the revival of trade: The law merchant, private judges, and the Champagne fairs." *Economics & Politics* 2, no. 1 (1990): 1-23.

Mohr, Lawrence B. "Organizations, decisions, and courts." *Law & Society Review* 10, no. 4 (1976): 621-642.

Frank, Jerome. "What Courts Do in Fact." *Illinois Law Review* 26, no. 6 (1931): 645-666.

Kapiszewski, Diana, and Matthew M. Taylor. "Doing courts justice? Studying judicial politics in Latin America." *Perspectives on politics* 6, no. 4 (2008): 741-767.

Dahl, Robert A. "Decision-making in a democracy: The Supreme Court as a national policy-maker." *Journal of Public Law* 6, no. 2 (1957): 279.

## Lecture slides

<!-- [Week 1](lectures/01-reasons-courts.html) -->
