---
title: "4: Judicial Power and Independence"
---

Why does anyone pay attention to what courts have to say? In other words, what are the sources of judicial power? This week we consider different conceptions of judicial independence, their relation to attributes that make courts appear conventionally "powerful" and why international courts are frequently thought of as less powerful than domestic courts.

## Mandatory readings

Staton, Jeffrey K., and Will H. Moore. "Judicial power in domestic and international politics." *International Organization* 65, no. 3 (2011): 553-587.

## Optional readings

Vanberg, Georg. "Constitutional courts in comparative perspective: A theoretical assessment." *Annual Review of Political Science* 18, no. 1 (2015): 167-185.

Stiansen, Øyvind. "(Non) renewable Terms and Judicial Independence in the European Court of Human Rights." *The Journal of Politics* 84, no. 2 (2022): 992-1006.

Ghias, Shoaib. “Miscarriage of Chief Justice: Judicial Power and the Legal Complex in Pakistan under Musharraf." *Law & Social Inquiry* 35, no. 4 (2010): 985-1022.

Popova, Maria. "Political competition as an obstacle to judicial independence: Evidence from Russia and Ukraine." *Comparative Political Studies* 43, no. 10 (2010): 1202-1229.

Melton, James, and Tom Ginsburg. "Does de jure judicial independence really matter?: A reevaluation of explanations for judicial independence." *Journal of Law and Courts* 2, no. 2 (2014): 187-217.

Liu, Ernest, Yi Lu, Wenwei Peng, and Shaoda Wang. *Judicial independence, local protectionism, and economic integration: Evidence from China*. No. w30432. National Bureau of Economic Research, 2022.

## Lecture slides

[Week 4](lectures/04-judicial-power.html)
