---
title: "5: Appointing and Monitoring Judges"
---

A key mechanism through which politicians keep judges in check is the appointment procedure. This week we focus on the implications of institutional design choices of judicial appointment procedures, as well as what monitoring mechanisms governments can devise to keep abreast of how their appointees are deciding.

## Mandatory readings

Larsson, Olof, Theresa Squatrito, Øyvind Stiansen, and Taylor St John. "Selection and appointment in international adjudication: insights from political science." *Journal of International Dispute Settlement* 14, no. 2 (2023): 134-148.

## Optional readings

Voeten, Erik. "The politics of international judicial appointments: evidence from the European Court of Human Rights." *International Organization* 61, no. 4 (2007): 669-701.

Arrington, Nancy, Leeann Bass, Adam Glynn, Jeffrey K. Staton, Brian Delgado, and Staffan I. Lindberg. "Constitutional reform and the gender diversification of peak courts." *American Political Science Review* 115, no. 3 (2021): 851-868.

Kastellec, Jonathan P., Jeffrey R. Lax, and Justin H. Phillips. "Public opinion and senate confirmation of Supreme Court nominees." *The Journal of Politics* 72, no. 3 (2010): 767-784.

Elsig, Manfred, and Mark A. Pollack. "Agents, trustees, and international courts: The politics of judicial appointment at the World Trade Organization." *European Journal of International Relations* 20, no. 2 (2014): 391-415.

## Lecture slides

<!-- [Week 5](lectures/05-appoint-monitor.html) -->
