---
title: "2: Theories of Judicial Behaviour"
---

Court rulings have an impact on individuals, economies and political systems. In principle, judgments follow from legal rules. But how do judges make decisions in practice? This week we review the most influential theories of judicial behaviour, the conditions under which they apply and the evidence produced in their support.

## Mandatory readings

Harris, Allison P., and Maya Sen. "Bias and judging." *Annual Review of Political Science* 22, no. 1 (2019): 241-259.

## Optional readings

Dyevre, Arthur. "Unifying the field of comparative judicial politics: towards a general theory of judicial behaviour." *European Political Science Review* 2, no. 2 (2010): 297-327.

Choi, Donghyun Danny, J. Andrew Harris, and Fiona Shen-Bayh. "Ethnic bias in judicial decision making: Evidence from criminal appeals in Kenya." *American Political Science Review* 116, no. 3 (2022): 1067-1080.

Ash, Elliott, Sam Asher, Aditi Bhowmick, Sandeep Bhupatiraju, Daniel Chen, Tanaya Devi, Christoph Goessmann, Paul Novosad, and Bilal Siddiqi. "In-group bias in the Indian judiciary: Evidence from 5 million criminal cases." *Review of Economics and Statistics* (2025): 1-45.

Glynn, Adam N., and Maya Sen. "Identifying judicial empathy: Does having daughters cause judges to rule for women's issues?." *American Journal of Political Science* 59, no. 1 (2015): 37-54.

Voeten, Erik. "Gender and judging: evidence from the European Court of Human Rights." *Journal of European Public Policy* 28, no. 9 (2021): 1453-1473.

Boyd, Christina L., Lee Epstein, and Andrew D. Martin. "Untangling the causal effects of sex on judging." *American Journal of Political Science* 54, no. 2 (2010): 389-411.

Edelman, Lauren B., Linda H. Krieger, Scott R. Eliason, Catherine R. Albiston, and Virginia Mellema. "When organizations rule: Judicial deference to institutionalized employment structures." *American Journal of Sociology* 117, no. 3 (2011): 888-954.

Ash, Elliott, Daniel L. Chen, and Arianna Ornaghi. "Gender attitudes in the judiciary: Evidence from US circuit courts." *American Economic Journal: Applied Economics* 16, no. 1 (2024): 314-350.

Clark, Tom S., Benjamin G. Engst, and Jeffrey K. Staton. "Estimating the effect of leisure on judicial performance." *The Journal of Legal Studies* 47, no. 2 (2018): 349-390.

Posner, Richard A. "What do judges and justices maximize? (The same thing everybody else does)." *Supreme Court Economic Review* 3, no. 1 (1993): 1-41.

Engel, Christoph, and Keren Weinshall. "Manna from Heaven for Judges: Judges’ Reaction to a Quasi‐Random Reduction in Caseload." *Journal of Empirical Legal Studies* 17, no. 4 (2020): 722-751.

## Lecture slides

<!-- [Week 2](lectures/02-theories-judging.html) -->
