---
title: "8: Judicialization and Politicization"
---

Has politics become judicialized? Or have courts become politicized? What are the political implications of judicial empowerment? This week we examine normative and empirical arguments about the judicialization of politics and politicization of courts.

## Mandatory readings

Hirschl, Ran. "The political origins of judicial empowerment through constitutionalization: Lessons from four constitutional revolutions." *Law & Social Inquiry* 25, no. 1 (2000): 91-149.

## Optional readings

Whittington, Keith E. "“Interpose your friendly hand”: Political supports for the exercise of judicial review by the United States Supreme Court." *American Political Science Review* 99, no. 4 (2005): 583-596.

Abebe, Daniel, and Tom Ginsburg. "The dejudicialization of international politics?." *International Studies Quarterly* 63, no. 3 (2019): 521-530.

Moravcsik, Andrew. "The origins of human rights regimes: Democratic delegation in postwar Europe." *International Organization* 54, no. 2 (2000): 217-252.

Ferejohn, John. "Judicializing politics, politicizing law." *Law and contemporary problems* 65, no. 3 (2002): 41-68.

Goldstein, Leslie Friedman. "From democracy to juristocracy." *Law & society review* 38, no. 3 (2004): 611-629.

Hirschl, Ran. "The judicialization of mega-politics and the rise of political courts." *Annual Review of Political Science* 11, no. 1 (2008): 93-118.

Domingo, Pilar. "Judicialization of politics or politicization of the judiciary? Recent trends in Latin America." *Democratization* 11, no. 1 (2004): 104-126.

## Lecture slides

<!-- [Week 8](lectures/08-judicialization.html) -->
