---
title: "6: Courts, Executives and Legislatures"
---

What is the relationship between courts, legislatures and executives? The first thing that often comes to mind is that courts are independent from the other branches, an assumption that is tested in many authoritarian regimes. This week we look at how inter-branch relations work in practice across different contexts, with an emphasis on the role of anticipatory behaviours.

## Mandatory readings

Pavone, Tommaso, and Øyvind Stiansen. "The shadow effect of courts: Judicial review and the politics of preemptive reform." *American Political Science Review* 116, no. 1 (2022): 322-336.

## Optional readings

Vanberg, Georg. "Legislative-judicial relations: A game-theoretic approach to constitutional review." *American Journal of Political Science* (2001): 346-361.

Helmke, Gretchen. "The logic of strategic defection: Court–executive relations in Argentina under dictatorship and democracy." *American Political Science Review* 96, no. 2 (2002): 291-303.

Helmke, Gretchen, and Frances Rosenbluth. "Regimes and the rule of law: Judicial independence in comparative perspective." *Annual Review of Political Science* 12, no. 1 (2009): 345-366.

Larsson, Olof, and Daniel Naurin. "Judicial independence and political uncertainty: how the risk of override affects the Court of Justice of the EU." *International Organization* 70, no. 2 (2016): 377-408.

Busch, Marc L., and Krzysztof J. Pelc. "The politics of judicial economy at the World Trade Organization." *International Organization* 64, no. 2 (2010): 257-279.

Schroeder, Philipp. "Pushing boundaries: How lawmakers shape judicial decision-making." *Comparative Political Studies* 55, no. 14 (2022): 2447-2479.

Segal, Jeffrey A. "Separation-of-powers games in the positive theory of congress and courts." *American Political Science Review* 91, no. 1 (1997): 28-44.

Segal, Jeffrey A., Chad Westerland, and Stefanie A. Lindquist. "Congress, the Supreme Court, and judicial review: Testing a constitutional separation of powers model." *American Journal of Political Science* 55, no. 1 (2011): 89-104.

Solomon, Peter H. "Review of *Courts and Judges in Authoritarian Regimes*, by Lisa Hilbink, Tamir Moustafa, and Anthony W. Pereira." *World Politics* 60, no. 1 (2007): 122–45.

## Lecture slides

[Week 6](lectures/06-executive-legislature.html)
