---
title: "9: Legal Mobilization and Judicial Impact"
---

Under what conditions do interest groups resort to litigation and what makes their success likely? As "passive" institutions, courts rely on legal mobilization for influence. This week we explore the dynamics of legal mobilization and how the size and structure of the judicial docket conditions courts' policy impact.

## Mandatory readings

Vanhala, Lisa. "Is legal mobilization for the birds? Legal opportunity structures and environmental nongovernmental organizations in the United Kingdom, France, Finland, and Italy." *Comparative Political Studies* 51, no. 3 (2018): 380-412.

## Optional readings

De Fazio, Gianluca. "Legal opportunity structure and social movement strategy in Northern Ireland and southern United States." *International Journal of Comparative Sociology* 53, no. 1 (2012): 3-22.

Kahraman, Filiz. "What makes an international institution work for labor activists? Shaping international law through strategic litigation." *Law & Society Review* 57, no. 1 (2023): 61-82.

González Ocantos, Ezequiel. "Persuade them or oust them: Crafting judicial change and transitional justice in Argentina." *Comparative politics* 46, no. 4 (2014): 479-498.

Gallagher, Janice. "The last mile problem: Activists, advocates, and the struggle for justice in domestic courts." *Comparative Political Studies* 50, no. 12 (2017): 1666-1698.

Pavone, Tommaso. "From Marx to market: Lawyers, European Law, and the contentious transformation of the Port of Genoa." *Law & Society Review* 53, no. 3 (2019): 851-888.

Helfer, Laurence R., and Erik Voeten. "International courts as agents of legal change: Evidence from LGBT rights in Europe." *International Organization* 68, no. 1 (2014): 77-110.

Gauri, Varun, Jeffrey K. Staton, and Jorge Vargas Cullell. "The Costa Rican Supreme Court’s compliance monitoring system." *The Journal of Politics* 77, no. 3 (2015): 774-786.

Hermansen, Silje Synnøve Lyder, Tommaso Pavone, and Louisa Boulaziz. "Leveling and Spotlighting: How the European Court of Justice Favors the Weak to Promote Its Legitimacy." *British Journal of Political Science* 55 (2025): e158.

## Lecture slides

[Week 9](lectures/09-legal-mobilization.html)
